baseURL: https://reforme.ch/
languageCode: fr
title: reforme.ch

taxonomies:
  tag: tags
  cantons: cantons

RemovePathAccents: true

disableKinds:
  - RSS

minify:
  minifyOutput: true

params:
  footer: |
    auteur: [Nicolas Friedli](https://theologique.ch/) / moteur: [Hugo](https://gohugo.io/) / sources: [GitHub](https://github.com/nfriedli/reforme.ch) / couleurs: [Max Böck](https://mxb.dev/blog/color-theme-switcher/)  

related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
  - name: tags
    weight: 50
  - name: cantons
    weight: 90
  - name: keywords
    weight: 100