baseURL: https://reforme.ch/
languageCode: fr
defaultContentLanguage: fr
title: reforme.ch

taxonomies:
  tag: tags
  canton: cantons

enableGitInfo: true

canonifyURLs: true

RemovePathAccents: true

# googleAnalytics: UA-162767126-4

disableKinds:
  - robotsTXT
  - 404

minify:
  minifyOutput: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

markup:
  highlight:
    codeFences: true
    style: dracula

params:
  footer: |
    [À propos de ce site](/about/)  
    
    [Flux RSS](/feeds/)
  title: reforme.ch
  description: Le protestantisme réformé de Suisse romande en réseau
  images:
    - https://cdn.pixabay.com/photo/2016/06/11/23/22/soap-bubbles-1451092_1280.jpg

related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
  - name: tags
    weight: 50
  - name: cantons
    weight: 60
  - name: keywords
    weight: 100
