baseURL: https://reforme.ch/
languageCode: fr
title: reforme.ch

taxonomies:
  tag: tags
  cantons: cantons

enableGitInfo: true

RemovePathAccents: true

googleAnalytics: UA-162767126-4

disableKinds:
  - RSS
  - robotsTXT
  - 404

minify:
  minifyOutput: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

params:
  footer: |
    [Ajouter un site](https://forms.gle/81etzY215AADgKuy7)
  footerHome: |
      auteur: [Nicolas Friedli](https://theologique.ch/) / moteur: [Hugo](https://gohugo.io/) / sources: [GitHub](https://github.com/nfriedli/reforme.ch) / hébergement: [Netlify](https://www.netlify.com/) / couleurs: [Max Böck](https://mxb.dev/blog/color-theme-switcher/)  
  title: reforme.ch
  description: Le protestantisme réformé de Suisse romande en réseau
  images:
    - https://cdn.pixabay.com/photo/2016/06/11/23/22/soap-bubbles-1451092_1280.jpg

related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
  - name: tags
    weight: 50
  - name: cantons
    weight: 60
  - name: keywords
    weight: 100