baseURL: https://reforme.ch/
languageCode: fr
defaultContentLanguage: fr
title: reforme.ch

enableGitInfo: true

RemovePathAccents: true

googleAnalytics: UA-162767126-4

disableKinds:
  - robotsTXT
  - 404
  - taxonomy
  - term


minify:
  minifyOutput: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

params:
  title: reforme.ch
  description:  à la découverte du protestantisme réformé
  footer: |
    Licence: CC by-sa  
    Contact: [Nicolas Friedli](mailto:nicolasfriedli@protonmail.ch "Contacter Nicolas Friedli par mail")  
  images:
    - https://cdn.pixabay.com/photo/2017/12/07/18/30/abandoned-building-3004317_1280.jpg