baseURL: https://reforme.ch/
languageCode: fr
defaultContentLanguage: fr
title: reforme.ch

enableGitInfo: true

RemovePathAccents: true

googleAnalytics: UA-162767126-4

disableKinds:
  - robotsTXT
  - 404

minify:
  minifyOutput: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

markup:
  highlight:
    codeFences: true
    style: dracula

params:
  footer: |
    Un blog par Nicolas Friedli
  title: reforme.ch
  description: Suite et fin des affaires courantes
  images:
    - https://cdn.pixabay.com/photo/2016/06/11/23/22/soap-bubbles-1451092_1280.jpg
