baseURL: https://reforme.ch/
languageCode: fr
title: reforme.ch

taxonomies:
  tag: tags
  cantons: cantons

RemovePathAccents: true

googleAnalytics: UA-162767126-4

disableKinds:
  - RSS
  - robotsTXT
  - 404

minify:
  minifyOutput: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

params:
  footer: |
    [Ajouter un site](https://forms.gle/81etzY215AADgKuy7)
  footerHome: |
      auteur: [Nicolas Friedli](https://theologique.ch/) / moteur: [Hugo](https://gohugo.io/) / sources: [GitHub](https://github.com/nfriedli/reforme.ch) / hébergement: [Netlify](https://www.netlify.com/) / couleurs: [Max Böck](https://mxb.dev/blog/color-theme-switcher/)  
  title: reforme.ch
  description: Le protestantisme réformé de Suisse romande en réseau
  images:
    - https://cdn.pixabay.com/photo/2016/02/19/11/24/chornobyl-1209692_960_720.jpg
    - https://cdn.pixabay.com/photo/2016/07/11/20/34/lost-places-1510592_960_720.jpg
    - https://cdn.pixabay.com/photo/2015/03/26/09/43/building-690177_960_720.jpg
    - https://cdn.pixabay.com/photo/2017/09/17/18/15/lost-places-2759275_960_720.jpg
    - https://cdn.pixabay.com/photo/2017/03/21/09/51/borgward-hansa-2161701_960_720.jpg

related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
  - name: tags
    weight: 50
  - name: cantons
    weight: 60
  - name: keywords
    weight: 100