---
label: Site
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: site
  label: site
- type: text
  name: description
  label: description
- type: image_gallery
  name: images
  label: images
- type: list
  name: tags
  label: tags
- type: list
  name: cantons
  label: cantons
- type: list
  name: avis
  label: avis
